import React from 'react'
import Modal from '../components/Modal'
import { useState } from 'react'

const ModalPage = () => {
    const [showModal, setShowModal] = useState(false)

    const handleClick = ()=>{
        setShowModal(true)
    }

    const handleClose = ()=>{
        setShowModal(false)
    }

    const actionbar = <div>
        <button className='px-3 py-1.5 border border-green-500 bg-green-300' onClick={handleClose}>I accept</button>
    </div>
  return (
    <div>
        <button className='px-3 py-1.5 border border-black' onClick={handleClick}>Open Modal</button>   
        { showModal && 
        
        <Modal onClose={handleClose} actionbar={actionbar}>
            <p>Here is an important agreement for you to read.</p>    
        </Modal>}
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam a odio massa. Suspendisse vitae posuere lectus. Proin vitae auctor nibh. Pellentesque consequat iaculis urna, et placerat eros dignissim ac. Praesent a tortor sed tellus tincidunt sollicitudin. Praesent eget ultrices augue. Fusce vehicula placerat lacus sed ultricies. Cras sed mauris tortor. Sed ligula quam, sagittis convallis porttitor a, auctor et nunc. Donec condimentum nisl ultricies nisi scelerisque tincidunt. Nunc at ornare magna, vel tristique urna. Nam a pharetra metus, non vulputate turpis. Ut convallis vitae est id rhoncus. Mauris ac justo ullamcorper, rhoncus enim eu, scelerisque enim. Maecenas egestas metus nec orci lobortis, a venenatis libero tincidunt. Sed in velit eget mauris rhoncus fringilla.</p>             
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam a odio massa. Suspendisse vitae posuere lectus. Proin vitae auctor nibh. Pellentesque consequat iaculis urna, et placerat eros dignissim ac. Praesent a tortor sed tellus tincidunt sollicitudin. Praesent eget ultrices augue. Fusce vehicula placerat lacus sed ultricies. Cras sed mauris tortor. Sed ligula quam, sagittis convallis porttitor a, auctor et nunc. Donec condimentum nisl ultricies nisi scelerisque tincidunt. Nunc at ornare magna, vel tristique urna. Nam a pharetra metus, non vulputate turpis. Ut convallis vitae est id rhoncus. Mauris ac justo ullamcorper, rhoncus enim eu, scelerisque enim. Maecenas egestas metus nec orci lobortis, a venenatis libero tincidunt. Sed in velit eget mauris rhoncus fringilla.</p>             
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam a odio massa. Suspendisse vitae posuere lectus. Proin vitae auctor nibh. Pellentesque consequat iaculis urna, et placerat eros dignissim ac. Praesent a tortor sed tellus tincidunt sollicitudin. Praesent eget ultrices augue. Fusce vehicula placerat lacus sed ultricies. Cras sed mauris tortor. Sed ligula quam, sagittis convallis porttitor a, auctor et nunc. Donec condimentum nisl ultricies nisi scelerisque tincidunt. Nunc at ornare magna, vel tristique urna. Nam a pharetra metus, non vulputate turpis. Ut convallis vitae est id rhoncus. Mauris ac justo ullamcorper, rhoncus enim eu, scelerisque enim. Maecenas egestas metus nec orci lobortis, a venenatis libero tincidunt. Sed in velit eget mauris rhoncus fringilla.</p>             
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam a odio massa. Suspendisse vitae posuere lectus. Proin vitae auctor nibh. Pellentesque consequat iaculis urna, et placerat eros dignissim ac. Praesent a tortor sed tellus tincidunt sollicitudin. Praesent eget ultrices augue. Fusce vehicula placerat lacus sed ultricies. Cras sed mauris tortor. Sed ligula quam, sagittis convallis porttitor a, auctor et nunc. Donec condimentum nisl ultricies nisi scelerisque tincidunt. Nunc at ornare magna, vel tristique urna. Nam a pharetra metus, non vulputate turpis. Ut convallis vitae est id rhoncus. Mauris ac justo ullamcorper, rhoncus enim eu, scelerisque enim. Maecenas egestas metus nec orci lobortis, a venenatis libero tincidunt. Sed in velit eget mauris rhoncus fringilla.</p>             
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam a odio massa. Suspendisse vitae posuere lectus. Proin vitae auctor nibh. Pellentesque consequat iaculis urna, et placerat eros dignissim ac. Praesent a tortor sed tellus tincidunt sollicitudin. Praesent eget ultrices augue. Fusce vehicula placerat lacus sed ultricies. Cras sed mauris tortor. Sed ligula quam, sagittis convallis porttitor a, auctor et nunc. Donec condimentum nisl ultricies nisi scelerisque tincidunt. Nunc at ornare magna, vel tristique urna. Nam a pharetra metus, non vulputate turpis. Ut convallis vitae est id rhoncus. Mauris ac justo ullamcorper, rhoncus enim eu, scelerisque enim. Maecenas egestas metus nec orci lobortis, a venenatis libero tincidunt. Sed in velit eget mauris rhoncus fringilla.</p>             
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam a odio massa. Suspendisse vitae posuere lectus. Proin vitae auctor nibh. Pellentesque consequat iaculis urna, et placerat eros dignissim ac. Praesent a tortor sed tellus tincidunt sollicitudin. Praesent eget ultrices augue. Fusce vehicula placerat lacus sed ultricies. Cras sed mauris tortor. Sed ligula quam, sagittis convallis porttitor a, auctor et nunc. Donec condimentum nisl ultricies nisi scelerisque tincidunt. Nunc at ornare magna, vel tristique urna. Nam a pharetra metus, non vulputate turpis. Ut convallis vitae est id rhoncus. Mauris ac justo ullamcorper, rhoncus enim eu, scelerisque enim. Maecenas egestas metus nec orci lobortis, a venenatis libero tincidunt. Sed in velit eget mauris rhoncus fringilla.</p>             
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam a odio massa. Suspendisse vitae posuere lectus. Proin vitae auctor nibh. Pellentesque consequat iaculis urna, et placerat eros dignissim ac. Praesent a tortor sed tellus tincidunt sollicitudin. Praesent eget ultrices augue. Fusce vehicula placerat lacus sed ultricies. Cras sed mauris tortor. Sed ligula quam, sagittis convallis porttitor a, auctor et nunc. Donec condimentum nisl ultricies nisi scelerisque tincidunt. Nunc at ornare magna, vel tristique urna. Nam a pharetra metus, non vulputate turpis. Ut convallis vitae est id rhoncus. Mauris ac justo ullamcorper, rhoncus enim eu, scelerisque enim. Maecenas egestas metus nec orci lobortis, a venenatis libero tincidunt. Sed in velit eget mauris rhoncus fringilla.</p>             
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam a odio massa. Suspendisse vitae posuere lectus. Proin vitae auctor nibh. Pellentesque consequat iaculis urna, et placerat eros dignissim ac. Praesent a tortor sed tellus tincidunt sollicitudin. Praesent eget ultrices augue. Fusce vehicula placerat lacus sed ultricies. Cras sed mauris tortor. Sed ligula quam, sagittis convallis porttitor a, auctor et nunc. Donec condimentum nisl ultricies nisi scelerisque tincidunt. Nunc at ornare magna, vel tristique urna. Nam a pharetra metus, non vulputate turpis. Ut convallis vitae est id rhoncus. Mauris ac justo ullamcorper, rhoncus enim eu, scelerisque enim. Maecenas egestas metus nec orci lobortis, a venenatis libero tincidunt. Sed in velit eget mauris rhoncus fringilla.</p>             
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam a odio massa. Suspendisse vitae posuere lectus. Proin vitae auctor nibh. Pellentesque consequat iaculis urna, et placerat eros dignissim ac. Praesent a tortor sed tellus tincidunt sollicitudin. Praesent eget ultrices augue. Fusce vehicula placerat lacus sed ultricies. Cras sed mauris tortor. Sed ligula quam, sagittis convallis porttitor a, auctor et nunc. Donec condimentum nisl ultricies nisi scelerisque tincidunt. Nunc at ornare magna, vel tristique urna. Nam a pharetra metus, non vulputate turpis. Ut convallis vitae est id rhoncus. Mauris ac justo ullamcorper, rhoncus enim eu, scelerisque enim. Maecenas egestas metus nec orci lobortis, a venenatis libero tincidunt. Sed in velit eget mauris rhoncus fringilla.</p>             
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam a odio massa. Suspendisse vitae posuere lectus. Proin vitae auctor nibh. Pellentesque consequat iaculis urna, et placerat eros dignissim ac. Praesent a tortor sed tellus tincidunt sollicitudin. Praesent eget ultrices augue. Fusce vehicula placerat lacus sed ultricies. Cras sed mauris tortor. Sed ligula quam, sagittis convallis porttitor a, auctor et nunc. Donec condimentum nisl ultricies nisi scelerisque tincidunt. Nunc at ornare magna, vel tristique urna. Nam a pharetra metus, non vulputate turpis. Ut convallis vitae est id rhoncus. Mauris ac justo ullamcorper, rhoncus enim eu, scelerisque enim. Maecenas egestas metus nec orci lobortis, a venenatis libero tincidunt. Sed in velit eget mauris rhoncus fringilla.</p>             

    </div>
  )
}

export default ModalPage